---
title: "R Notebook"
output: html_notebook
---

A Titanic katasztrófa túlélésének predikciója

Adatok beolvasása, előkészítése:

```{r}
library(readr)
gender_submission <- read.csv("gender_submission.csv")
View(gender_submission)
train <- read_csv("train.csv", 
     col_types = cols(
         Sex = col_factor(levels = c("male", "female")),
         Age = col_double(), 
         Embarked = col_factor(levels = c("C", "S", "Q")), 
         Parch = col_integer(), 
         Pclass = col_factor(levels = c("3", "2", "1"), ordered = TRUE), 
         SibSp = col_integer(), 
         Survived = col_integer()))
test <- read_csv("test.csv", 
     col_types = cols(
         Sex = col_factor(levels = c("male", "female")),
         Age = col_double(), 
         Embarked = col_factor(levels = c("C", "S", "Q")), 
         Parch = col_integer(), 
         Pclass = col_factor(levels = c("3", "2", "1"), ordered = TRUE), 
         SibSp = col_integer()))
View(test)
```


```{r}
str(train)
```


Csomagok, előkészítés
```{r, warning=FALSE}
library(mice)
library(caret)
library(splines)
library(glmnet)
library(nnet)
library(rpart)
library(randomForest)
library(gbm)
library(caretEnsemble)
library(ModelMetrics)
library(plotmo)
library(plyr)
library(ggplot2)
library(gmodels)

traink <- dummyVars("~ Sex + Embarked", data = train)
traink <- data.frame(predict(traink, newdata = train))
traink$Pclass <- train$Pclass
traink$Age <- train$Age
traink$SibSp <- train$SibSp
traink$Parch <- train$Parch
traink$Fare <- train$Fare
traink$Survived <- train$Survived
set.seed(1912)
traink <- complete(mice(traink, method="rf", m=1))
View(traink)

testk <- dummyVars("~ Sex + Embarked", data = test)
testk <- data.frame(predict(testk, newdata = test))
testk$Pclass <- test$Pclass
testk$Age <- test$Age
testk$SibSp <- test$SibSp
testk$Parch <- test$Parch
testk$Fare <- test$Fare
set.seed(1912)
testk <- complete(mice(testk, method="rf", m=1))
View(testk)
```

Ábrázolás
```{r}
 ggplot(data=traink, aes(Fare))+geom_histogram()
 ggplot(data=traink, aes(Age))+geom_histogram()
 ggplot(data=traink, aes(Survived))+geom_bar()
```


Modellek
```{r}
 library(rattle)
 keresztval <- trainControl(method="cv", number=5)
 fa <- train(as.factor(Survived)~., data=traink, method="rpart", trControl=keresztval)
 fa # cp=0.01461988 esetén Accuracy=0.8002134, Kappa=0.5708988
 #plot(fa$finalModel)
 #text(fa$finalModel)
 fancyRpartPlot(fa$finalModel)
```
```{r}
 mtry <- data.frame(mtry=1:10)
 erdo <- train(as.factor(Survived)~., data=traink, method="rf", trControl=keresztval, ntree=30, tuneGrid=mtry)
 erdo # mtry=4 esetén Accuracy=0.8440274, Kappa=0.6614112
 plot(erdo$finalModel) # ez nem rendes erdőrajz, de olyat careten belül nem találtam
```

```{r}
 gboost <- train(as.factor(Survived)~., data=traink, method="gbm", trControl=keresztval)
 gboost # n.trees = 150, interaction.depth = 2, shrinkage = 0.1 and n.minobsinnode = 10 esetén Accuracy=0.8249262, Kappa=0.6225874
```

```{r}
#??? vagy az a baja, hogy nem bináris a változó, vagy az, hogy amikor bináris, akkor a kategóriák nevében szám áll az első helyen; szóval nem tudom, mit kezdjek vele
 control <- trainControl(method="cv", number=5, index = createFolds(traink$Survived, 5), savePredictions="final")
 levels(traink$Survived)=c("Yes","No")
 traink %>% mutate(Survived = factor(Survived,labels = make.names(levels(Survived))))
 modellek <- caretList(Survived~., data=traink, methodList=c("rpart","rf","glmnet"), trControl=control)
 szuper <- caretStack(modellek, method="logreg", trControl=control)
 szuper
```

```{r}
 hyper <- data.frame(n.trees = 150, interaction.depth = 2, shrinkage = 0.1, n.minobsinnode = 10)
 gboost_best <- train(as.factor(Survived)~., data=traink, method="gbm", trControl=keresztval, tuneGrid=hyper)
 mtry <- data.frame(mtry=4)
 erdo_best <- train(as.factor(Survived)~., data=traink, method="rf", trControl=keresztval, ntree=30, tuneGrid=mtry)
 summary(gboost_best)
 gboost_best # Accuracy=0.8248481, Kappa=0.6215871
 summary(erdo_best)
 erdo_best # Accuracy=0.8384265, Kappa=0.6501237
 
```

Változók fontossága, becslés
```{r}
 fontos_gboost <- varImp(gboost_best)
 fontos_gboost <- fontos_gboost$importance
 plot(varImp(gboost_best))
```
```{r}
 fontos_erdo <- varImp(erdo_best)
 fontos_erdo <- fontos_erdo$importance
 plot(varImp(erdo_best))
```
```{r}
 becsultgb <- predict(gboost_best, testk)
 CrossTable(becsultgb,gender_submission$Survived)
```
```{r}
 becsulterdo <- predict(erdo_best, testk)
 CrossTable(becsulterdo,gender_submission$Survived)
```








